create a dataframe using np.random.rand function with 5 rows and 4 columns and perform various operations using pandas library

In [1]:
import pandas as pd
import numpy as np

In [3]:
a= np.random.rand(5,5)

In [4]:
a

array([[0.36213474, 0.73849951, 0.29519488, 0.40088468, 0.81380169],
       [0.07944747, 0.32928065, 0.31695807, 0.66929867, 0.71713138],
       [0.16006889, 0.34792552, 0.93012055, 0.94095856, 0.09672937],
       [0.51350361, 0.0821075 , 0.61640181, 0.00511439, 0.38469489],
       [0.75593476, 0.0135035 , 0.03354386, 0.30841786, 0.82777506]])

In [6]:
df= pd.DataFrame(np.random.rand(5,5), index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4','column5'])

In [7]:
df

column1   column2   column3   column4   column5
row1  0.178780  0.920643  0.501816  0.983215  0.550805
row2  0.574543  0.775354  0.184688  0.109905  0.540955
row3  0.116803  0.625295  0.053956  0.164191  0.841587
row4  0.747963  0.523414  0.075470  0.244500  0.097586
row5  0.326420  0.062926  0.249029  0.652515  0.492887

In [8]:
df.head()

column1   column2   column3   column4   column5
row1  0.178780  0.920643  0.501816  0.983215  0.550805
row2  0.574543  0.775354  0.184688  0.109905  0.540955
row3  0.116803  0.625295  0.053956  0.164191  0.841587
row4  0.747963  0.523414  0.075470  0.244500  0.097586
row5  0.326420  0.062926  0.249029  0.652515  0.492887

In [9]:
df['column3']

row1    0.501816
row2    0.184688
row3    0.053956
row4    0.075470
row5    0.249029
Name: column3, dtype: float64

In [10]:
df[['column2','column3']]

column2   column3
row1  0.920643  0.501816
row2  0.775354  0.184688
row3  0.625295  0.053956
row4  0.523414  0.075470
row5  0.062926  0.249029

In [11]:
df.loc['row1']

column1    0.178780
column2    0.920643
column3    0.501816
column4    0.983215
column5    0.550805
Name: row1, dtype: float64

In [12]:
type(df.loc['row1'])

pandas.core.series.Series

In [13]:
df.iloc[:,:]

column1   column2   column3   column4   column5
row1  0.178780  0.920643  0.501816  0.983215  0.550805
row2  0.574543  0.775354  0.184688  0.109905  0.540955
row3  0.116803  0.625295  0.053956  0.164191  0.841587
row4  0.747963  0.523414  0.075470  0.244500  0.097586
row5  0.326420  0.062926  0.249029  0.652515  0.492887

In [14]:
df.iloc[:,2:]

column3   column4   column5
row1  0.501816  0.983215  0.550805
row2  0.184688  0.109905  0.540955
row3  0.053956  0.164191  0.841587
row4  0.075470  0.244500  0.097586
row5  0.249029  0.652515  0.492887

In [15]:
df.iloc[:,2:].values

array([[0.50181624, 0.98321506, 0.55080453],
       [0.18468815, 0.10990451, 0.5409546 ],
       [0.05395605, 0.16419138, 0.84158747],
       [0.07547027, 0.24449957, 0.0975859 ],
       [0.24902923, 0.65251516, 0.4928865 ]])

In [16]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
column5    0
dtype: int64

In [17]:
df['column1'].value_counts()

0.116803    1
0.574543    1
0.747963    1
0.326420    1
0.178780    1
Name: column1, dtype: int64

In [18]:
df['column1'].unique()

array([0.17877977, 0.57454274, 0.11680266, 0.74796327, 0.32641988])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  5 non-null      float64
 1   column2  5 non-null      float64
 2   column3  5 non-null      float64
 3   column4  5 non-null      float64
 4   column5  5 non-null      float64
dtypes: float64(5)
memory usage: 412.0+ bytes


In [20]:
df.describe()

column1   column2   column3   column4   column5
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.388902  0.581526  0.212992  0.430865  0.504764
std    0.267152  0.326653  0.180086  0.375194  0.265902
min    0.116803  0.062926  0.053956  0.109905  0.097586
25%    0.178780  0.523414  0.075470  0.164191  0.492887
50%    0.326420  0.625295  0.184688  0.244500  0.540955
75%    0.574543  0.775354  0.249029  0.652515  0.550805
max    0.747963  0.920643  0.501816  0.983215  0.841587

In [21]:
df[df['column4']>0.5]

column1   column2   column3   column4   column5
row1  0.17878  0.920643  0.501816  0.983215  0.550805
row5  0.32642  0.062926  0.249029  0.652515  0.492887

In [22]:
df.corr

<bound method DataFrame.corr of        column1   column2   column3   column4   column5
row1  0.178780  0.920643  0.501816  0.983215  0.550805
row2  0.574543  0.775354  0.184688  0.109905  0.540955
row3  0.116803  0.625295  0.053956  0.164191  0.841587
row4  0.747963  0.523414  0.075470  0.244500  0.097586
row5  0.326420  0.062926  0.249029  0.652515  0.492887>

In [24]:
df.drop(index='row5',columns='column5')

column1   column2   column3   column4
row1  0.178780  0.920643  0.501816  0.983215
row2  0.574543  0.775354  0.184688  0.109905
row3  0.116803  0.625295  0.053956  0.164191
row4  0.747963  0.523414  0.075470  0.244500